server:
  port: 9999
  servlet:
    context-path: /uaa

spring:
  application:
    name: auth
  profiles:
    active: dev

feign:
  hystrix:
    enabled: true
ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000