spring:
  cloud:
    consul:
      host: localhost
      discovery:
        register: true
        prefer-ip-address: true
  redis:
    host: ${REDIS_HOST:192.168.2.176}
    port: 6379
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 20
        # 连接池中的最小空闲连接
        min-idle: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.10.1.28:3307/my_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1 FROM DUAL
    time-between-eviction-runs-millis: 300000
    min-evictable-idle-time-millis: 1800000